# Generated by Django 2.2.7 on 2019-11-29 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20191127_2056'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('content', '0004_post_subtitle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceManual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_filename', models.CharField(max_length=100)),
                ('fsm_file', models.FileField(upload_to='service_manuals')),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.Vehicle')),
            ],
        ),
    ]
