# Generated by Django 2.2.7 on 2019-11-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_servicemanual'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
