# Generated by Django 2.2.7 on 2019-11-29 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, choices=[(1, 'specs'), (2, 'mechanical'), (3, 'interior'), (4, 'exterior'), (5, 'miscellaneous')], max_length=50, null=True),
        ),
    ]
