# Generated by Django 2.2.7 on 2019-11-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='manufacturer',
            field=models.TextField(choices=[('Acura', 'Acura'), ('Alpha Romero', 'Alpha Romero'), ('Aston Martin', 'Aston Martin'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('Buick', 'Buick'), ('Bmw', 'Bmw'), ('Cadillac', 'Cadillac'), ('Chevrolet', 'Chevrolet'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Daihatsu', 'Daihatsu'), ('Datsun', 'Datsun'), ('Dodge', 'Dodge'), ('Eagle', 'Eagle'), ('Ferrari', 'Ferrari'), ('Fiat', 'Fiat'), ('Ford', 'Ford'), ('Gmc', 'Gmc'), ('Holden', 'Holden'), ('Honda', 'Honda'), ('Hummer', 'Hummer'), ('Hyundai', 'Hyundai'), ('Infiniti', 'Infiniti'), ('Jaguar', 'Jaguar'), ('Jeep', 'Jeep'), ('Kia', 'Kia'), ('Lamborghini', 'Lamborghini'), ('Land Rover', 'Land Rover'), ('Lexus', 'Lexus'), ('Lotus', 'Lotus'), ('Maserati', 'Maserati'), ('Mazda', 'Mazda'), ('Mclaren', 'Mclaren'), ('Mercedes-Benz', 'Mercedes-Benz'), ('Mercury', 'Mercury'), ('Mg', 'Mg'), ('Mini', 'Mini'), ('Mitsubishi', 'Mitsubishi'), ('Nissan', 'Nissan'), ('Oldsmobile', 'Oldsmobile'), ('Opel', 'Opel'), ('Peugeot', 'Peugeot'), ('Plymouth', 'Plymouth'), ('Pontiac', 'Pontiac'), ('Porsche', 'Porsche'), ('Renault', 'Renault'), ('Rolls-Royce', 'Rolls-Royce'), ('Saab', 'Saab'), ('Scion', 'Scion'), ('Seat', 'Seat'), ('Shelby', 'Shelby'), ('Smart', 'Smart'), ('Subaru', 'Subaru'), ('Suzuki', 'Suzuki'), ('Tesla', 'Tesla'), ('Toyota', 'Toyota'), ('Triumph', 'Triumph'), ('Vauxhall', 'Vauxhall'), ('Volkswagen', 'Volkswagen'), ('Volvo', 'Volvo')]),
        ),
    ]
