# Generated by Django 2.2.7 on 2019-12-06 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_auto_20191127_2056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleprofile',
            old_name='vehicle',
            new_name='context',
        ),
    ]
